import {
  ArticleContentContainer,
  FullSizeImage,
  Section,
  SectionHeader,
} from "../components/StyledComponents";

const HouseTour2024: React.FunctionComponent = () => {
  return (
    <ArticleContentContainer>
      <Section>
        <p></p>
      </Section>
      <Section>
        <SectionHeader>Entryway</SectionHeader>
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/entryway.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/sofa_table.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/entryway_wall_1.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/entryway_wall_2.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/entryway_wall_3.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/entryway_wall_4.jpeg`}
        />
      </Section>
      <Section>
        <SectionHeader>Living Room</SectionHeader>
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/living_room.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/living_room_2.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/living_room_3.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/living_room_wall_1.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/living_room_wall_2.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/living_room_wall_3.jpeg`}
        />
      </Section>
      <Section>
        <SectionHeader>Dining Room</SectionHeader>
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/dining_room.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/dining_room_1.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/dining_room_2.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/dining_room_3.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/dining_room_4.jpeg`}
        />
      </Section>
      <Section>
        <SectionHeader>Kitchen</SectionHeader>
      </Section>
      <Section>
        <SectionHeader>Bedroom</SectionHeader>
      </Section>
      <Section>
        <SectionHeader>Hobby Room</SectionHeader>
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/hobby_room.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/hobby_room_1.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/grow_lights_feb_2024.jpeg`}
        />
      </Section>
      <Section>
        <SectionHeader>Library</SectionHeader>
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/library.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/library_wall_1.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/library_wall_2.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/library_wall_3.jpeg`}
        />
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/library_wall_4.jpeg`}
        />
      </Section>
      <Section>
        <SectionHeader>Outside</SectionHeader>
        <FullSizeImage
          src={`${process.env.REACT_APP_IMAGES_BASE_URL}/front_of_house_2024.jpeg`}
        />
      </Section>
    </ArticleContentContainer>
  );
};

export default HouseTour2024;
