"""Add more book club tables

Revision ID: 5eabd213c86c
Revises: 7e3acfc6a823
Create Date: 2024-05-15 14:29:32.449489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eabd213c86c'
down_revision: Union[str, None] = '7e3acfc6a823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('reaction_id', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reaction_id'),
    schema='bookclub'
    )
    op.create_table('comment_reactions',
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('reaction_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], ),
    sa.ForeignKeyConstraint(['reaction_id'], ['bookclub.reactions.reaction_id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'reaction_id'),
    schema='bookclub'
    )
    op.create_table('comment_read_state',
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('read_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], ),
    sa.PrimaryKeyConstraint('comment_id'),
    schema='bookclub'
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['bookclub.books.book_id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    schema='bookclub'
    )
    op.create_table('thread_participants',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['bookclub.threads.thread_id'], ),
    sa.PrimaryKeyConstraint('thread_id'),
    schema='bookclub'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_participants', schema='bookclub')
    op.drop_table('reviews', schema='bookclub')
    op.drop_table('comment_read_state', schema='bookclub')
    op.drop_table('comment_reactions', schema='bookclub')
    op.drop_table('reactions', schema='bookclub')
    # ### end Alembic commands ###
