"""Create newsletter table

Revision ID: 3bd7ab6b5eba
Revises: ee0dcb81162c
Create Date: 2024-02-07 21:20:38.853518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd7ab6b5eba'
down_revision: Union[str, None] = 'ee0dcb81162c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter',
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter')
    # ### end Alembic commands ###
