"""Move start and end dates to book

Revision ID: d5cbfa9346a4
Revises: c66c281dfe8e
Create Date: 2024-05-16 09:02:21.307040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5cbfa9346a4'
down_revision: Union[str, None] = 'c66c281dfe8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False), schema='bookclub')
    op.add_column('books', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False), schema='bookclub')
    op.drop_column('threads', 'start_date', schema='bookclub')
    op.drop_column('threads', 'end_date', schema='bookclub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='bookclub')
    op.add_column('threads', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='bookclub')
    op.drop_column('books', 'end_date', schema='bookclub')
    op.drop_column('books', 'start_date', schema='bookclub')
    # ### end Alembic commands ###
