"""Add book title

Revision ID: 169606bf7f8c
Revises: abc72dcfba41
Create Date: 2024-05-16 07:47:53.880775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169606bf7f8c'
down_revision: Union[str, None] = 'abc72dcfba41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.String(), nullable=False), schema='bookclub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'title', schema='bookclub')
    # ### end Alembic commands ###
