"""Remove reactions

Revision ID: 7fb4b49d1d0a
Revises: 5eabd213c86c
Create Date: 2024-05-15 22:16:48.511152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb4b49d1d0a'
down_revision: Union[str, None] = '5eabd213c86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_reactions_reaction_id_fkey', 'comment_reactions', schema='bookclub', type_='foreignkey')
    op.drop_table('reactions', schema='bookclub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('comment_reactions_reaction_id_fkey', 'comment_reactions', 'reactions', ['reaction_id'], ['reaction_id'], source_schema='bookclub', referent_schema='bookclub')
    op.create_table('reactions',
    sa.Column('reaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('reaction_id', name='reactions_pkey'),
    schema='bookclub'
    )
    # ### end Alembic commands ###
