"""Add parent and children to comments

Revision ID: 7bd2183460b3
Revises: 384db0d58315
Create Date: 2024-05-24 07:40:58.178027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd2183460b3'
down_revision: Union[str, None] = '384db0d58315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
