"""Auto-increment ids

Revision ID: c66c281dfe8e
Revises: 169606bf7f8c
Create Date: 2024-05-16 08:53:26.925448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c66c281dfe8e'
down_revision: Union[str, None] = '169606bf7f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('threads_book_id_fkey', 'threads', schema='bookclub')
    op.drop_constraint('reviews_book_id_fkey', 'reviews', schema='bookclub')
    op.drop_constraint('reviews_comment_id_fkey', 'reviews', schema="bookclub")
    op.drop_constraint('comment_reactions_comment_id_fkey', 'comment_reactions', schema='bookclub')


    op.drop_table('comment_read_state', schema='bookclub')
    op.drop_table('books', schema='bookclub')
    op.drop_table('comments', schema='bookclub')
    op.drop_table('comment_reactions', schema='bookclub')
    op.drop_table('thread_participants', schema='bookclub')
    op.drop_table('reviews', schema='bookclub')
    op.drop_table('threads', schema='bookclub')

    op.create_table('books',
    sa.Column('book_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('book_id', name='books_pkey'),
    schema='bookclub',
    postgresql_ignore_search_path=False
    )
    op.create_table('threads',
    sa.Column('thread_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_comment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['bookclub.books.book_id'], name='threads_book_id_fkey'),
    sa.PrimaryKeyConstraint('thread_id', name='threads_pkey'),
    schema='bookclub',
    postgresql_ignore_search_path=False
    )
    op.create_table('thread_participants',
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['bookclub.threads.thread_id'], name='thread_participants_thread_id_fkey'),
    sa.PrimaryKeyConstraint('thread_id', name='thread_participants_pkey'),
    schema='bookclub'
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['bookclub.comments.comment_id'], name='comments_parent_comment_id_fkey'),
    sa.ForeignKeyConstraint(['thread_id'], ['bookclub.threads.thread_id'], name='fk_comments_thread_id_threads'),
    sa.PrimaryKeyConstraint('comment_id', name='comments_pkey'),
    schema='bookclub',
    postgresql_ignore_search_path=False
    )
    op.create_table('comment_reactions',
    sa.Column('comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], name='comment_reactions_comment_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', 'reaction_id', name='comment_reactions_pkey'),
    schema='bookclub'
    )
    op.create_table('comment_read_state',
    sa.Column('comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('read_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], name='comment_read_state_comment_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', name='comment_read_state_pkey'),
    schema='bookclub'
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['bookclub.books.book_id'], name='reviews_book_id_fkey'),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], name='reviews_comment_id_fkey'),
    sa.PrimaryKeyConstraint('review_id', name='reviews_pkey'),
    schema='bookclub'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_comment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['bookclub.books.book_id'], name='threads_book_id_fkey'),
    sa.PrimaryKeyConstraint('thread_id', name='threads_pkey'),
    schema='bookclub',
    postgresql_ignore_search_path=False
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['bookclub.books.book_id'], name='reviews_book_id_fkey'),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], name='reviews_comment_id_fkey'),
    sa.PrimaryKeyConstraint('review_id', name='reviews_pkey'),
    schema='bookclub'
    )
    op.create_table('thread_participants',
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['bookclub.threads.thread_id'], name='thread_participants_thread_id_fkey'),
    sa.PrimaryKeyConstraint('thread_id', name='thread_participants_pkey'),
    schema='bookclub'
    )
    op.create_table('comment_reactions',
    sa.Column('comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], name='comment_reactions_comment_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', 'reaction_id', name='comment_reactions_pkey'),
    schema='bookclub'
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['bookclub.comments.comment_id'], name='comments_parent_comment_id_fkey'),
    sa.ForeignKeyConstraint(['thread_id'], ['bookclub.threads.thread_id'], name='fk_comments_thread_id_threads'),
    sa.PrimaryKeyConstraint('comment_id', name='comments_pkey'),
    schema='bookclub',
    postgresql_ignore_search_path=False
    )
    op.create_table('books',
    sa.Column('book_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('book_id', name='books_pkey'),
    schema='bookclub',
    postgresql_ignore_search_path=False
    )
    op.create_table('comment_read_state',
    sa.Column('comment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('read_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['bookclub.comments.comment_id'], name='comment_read_state_comment_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', name='comment_read_state_pkey'),
    schema='bookclub'
    )
    # ### end Alembic commands ###
