"""Use username in comments table

Revision ID: 239d28898a5f
Revises: a88c84b9b05e
Create Date: 2024-02-19 11:21:31.009899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239d28898a5f'
down_revision: Union[str, None] = 'a88c84b9b05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
