"""Add featured flag

Revision ID: 384db0d58315
Revises: d099a1dcd1cc
Create Date: 2024-04-15 09:22:26.913858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384db0d58315'
down_revision: Union[str, None] = 'd099a1dcd1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('featured', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'featured')
    # ### end Alembic commands ###
