"""Add reaction and remove fk constraint on latest comment id

Revision ID: abc72dcfba41
Revises: 7fb4b49d1d0a
Create Date: 2024-05-15 22:29:14.140929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc72dcfba41'
down_revision: Union[str, None] = '7fb4b49d1d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_reactions', sa.Column('reaction', sa.Integer(), nullable=False), schema='bookclub')
    op.drop_constraint('threads_last_comment_id_fkey', 'threads', schema='bookclub', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('threads_last_comment_id_fkey', 'threads', 'comments', ['last_comment_id'], ['comment_id'], source_schema='bookclub', referent_schema='bookclub')
    op.drop_column('comment_reactions', 'reaction', schema='bookclub')
    # ### end Alembic commands ###
